// This is an autogenerated file from Firebase Genkit.
'use server';
/**
 * @fileOverview Analyzes a video for deepfake elements.
 *
 * - analyzeDeepfake - Analyzes a video for deepfake elements.
 * - AnalyzeDeepfakeInput - The input type for the analyzeDeepfake function.
 * - AnalyzeDeepfakeOutput - The return type for the analyzeDeepfake function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeDeepfakeInputSchema = z.object({
  frameDataUri: z
    .string()
    .describe(
      "An image frame from a video to analyze, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type AnalyzeDeepfakeInput = z.infer<typeof AnalyzeDeepfakeInputSchema>;

const AnalyzeDeepfakeOutputSchema = z.object({
  isDeepfake: z.boolean().describe('Whether the video is either a deepfake or fully AI-generated.'),
  deepfakeConfidence: z.number().describe('The confidence level that the video has been manipulated (e.g., face-swap) (0-1).'),
  aiGeneratedConfidence: z.number().describe('The confidence level that the video is entirely computer-generated (e.g., Veo, Sora) (0-1).'),
  analysis: z.string().describe('A detailed analysis of the video for deepfake elements, explaining the findings based on the provided frame.'),
});
export type AnalyzeDeepfakeOutput = z.infer<typeof AnalyzeDeepfakeOutputSchema>;

export async function analyzeDeepfake(input: AnalyzeDeepfakeInput): Promise<AnalyzeDeepfakeOutput> {
  return analyzeDeepfakeFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeDeepfakePrompt',
  input: {schema: AnalyzeDeepfakeInputSchema},
  output: {schema: AnalyzeDeepfakeOutputSchema},
  prompt: `You are a world-renowned expert in digital forensics, specializing in the detection of manipulated and AI-generated video. Your task is to analyze the provided image frame from a video with extreme scrutiny.

Image Frame: {{media url=frameDataUri}}

Based on this single frame, you must assess two possibilities:
1.  **Deepfake Manipulation:** The video is of a real scene/person but has been altered (e.g., face-swapping, lip-sync manipulation, object removal).
2.  **Fully AI-Generated:** The entire video is synthesized by an AI model (e.g., Google Veo, OpenAI Sora).

**Analysis Checklist:**
-   **Faces and Expressions:** Look for unnatural facial movements, lack of blinking, or inconsistent emotional expressions.
-   **Lighting and Shadows:** Analyze for inconsistent lighting sources, shadows that don\'t match objects, or reflections that behave incorrectly.
-   **Textures and Surfaces:** Scrutinize skin texture, hair, and clothing for a "plastic" or overly smooth appearance. Look for flickering or morphing textures.
-   **Background Details:** Examine the background for distorted or nonsensical details that a human filmmaker would not capture.
-   **Physics and Motion:** Look for unnatural object movement, odd physics, or unrealistic character motion (e.g., the "waxy" look of some generated humans).

**Response Format:**
Respond in a JSON format matching the schema.
-   \`isDeepfake\`: Set to \`true\` if either \`deepfakeConfidence\` or \`aiGeneratedConfidence\` is above 0.5.
-   \`deepfakeConfidence\`: Your confidence (0.0 to 1.0) that the video has been manipulated.
-   \`aiGeneratedConfidence\`: Your confidence (0.0 to 1.0) that the video was entirely generated by AI.
-   \`analysis\`: A detailed report on your findings, referencing specific points from the checklist. If you detect something, describe the visual evidence in the frame.
`,
});


const analyzeDeepfakeFlow = ai.defineFlow(
  {
    name: 'analyzeDeepfakeFlow',
    inputSchema: AnalyzeDeepfakeInputSchema,
    outputSchema: AnalyzeDeepfakeOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
